### ISSUE TITLE
Thoughts（一些遐思）, update continuously

### ISSUE THREAD

**Issue by barretlee** [barretlee/algorithms#13]
工作快两年时间了，这两年里我接触过很多系统和平台，也参与过不少系统和工程的建设，无论是编程能力还是沟通能力都有了质的飞跃。然而依然感觉缺了点什么。

技术和能力的成长有太多看得到的瓶颈，刚开始是因为缺乏知识和能力，看不到也摸不清一个领域的深度，这个时候如果不断地学习、不断地给大脑补给营养，两三年的时间会慢慢冲破这一层瓶颈。这个瓶颈期过了之后，再去学习新的知识提升就不明显了，如果你知道 log 函数曲线的走势，大概就能明白我的意思。所以第二个阶段重点不应该是狼吞虎咽地学习新技术，那些方法和经验会更加重要，参与到一些项目中，为项目的发展出谋划策，并不断在实践中留下沉淀和脚印，这样才能够在一个领域中走得更深、更远。

昨天跟 @wintercn 老湿促膝长谈，他给我了一些建议，我觉得挺有道理，不过还是觉得，学习依然是我的重心。过去两年更多的在提升自己的编程能力，在前端的知识边界上附近开荒，学的很浅薄。而今年需要沉下心来，把基本功打扎实。

所以你会慢慢发现，我今年的重心在对思维的训练上，主要分为两个方面，一是算法研究，二是系统性研究。算法的研究就跟机器学习一样，需要不断地做题、不断地挑战才能有突破，我相信这一块是熟能生巧，因为它很大部分都是硬知识，可以通过不断地学习来加深记忆，最近也在猛攻这些硬知识，希望在短时间内出点成效。而系统性的研究，还需要细细地琢磨，淘宝前端团队在工程和技术上领先国内绝大多数前端团队，领先可能不止半点丁点，按照 winter 的说法，差不多五年。所以问自己一个问题，假如有一个团队希望引入这些技术，我是否有能力 start from scratch？这里不仅仅是写代码的能力，还需要很强的工程能力和架构能力。

所以…努力吧！一切只是从零开始，后面的路还有很远。

**Comment by lessfish** [comment]
赞，看好小胡子哥

PS：有时想评论下小胡子哥的微博，发现好像评论不来= =

**Comment by mbpz** [comment]
赞

**Comment by mlyknown** [comment]
领先五年~~

**Comment by pengkobe** [comment]
榜样...
