### ISSUE TITLE
[每日一题] Two Sum

### ISSUE THREAD

**Issue by barretlee** [barretlee/algorithms#24]
给定一个整数数组，其中有两项之和为一个特定的数字，假设每次 input 只有一个唯一解，不允许两次使用同一个元素，返回这两个数的索引。

比如：

```js
给定 nums = [2, 7, 11, 15]，target = 9

由于 nums[0] + nums[1] = 9
所以返回 [0, 1]
```

**Comment by barretlee** [comment]
这里作答：https://github.com/barretlee/daily-algorithms/issues/1

**Comment by chechengpeng** [comment]
`function twoSum (nums,target) {
    for(var i=0;i<nums.length;i++) {
        for(var j=i+1;j<nums.length;j++){
            if(nums[i] + nums[j] == target) {
                return [i,j]
            }
        }
    }
}`

**Comment by chechengpeng** [comment]
``` 
function twoSum (nums,target) {
    for(var i=0;i<nums.length;i++) {
        for(var j=i+1;j<nums.length;j++){
            if(nums[i] + nums[j] == target) {
                return [i,j]
            }
        }
    }
}
```

**Comment by barretlee** [comment]
在 https://github.com/barretlee/daily-algorithms/issues/1 这里作答，可以考虑下是否有更快的方式。@chechengpeng
